src/cadet_logbook/urls.py
from .import views
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = views.error_404_view
handler500 = views.error_500_view

src/core/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'core' 

urlpatterns = [
    path('', LoginView.as_view(template_name='core/login.html'), name='home'),
    path('account/auth/logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('account/auth/password-reset/', PasswordResetView.as_view(template_name='core/password_reset_form.html',
                                                           success_url='/account/auth/password-reset/done',
                                                           email_template_name='account/password_reset_email.html'),
                                                           name='forgotpassword'),
          
    path('account/auth/password-reset/done', PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),
    path('account/auth/password-reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html',
                                          success_url='/account/auth/password-reset/complete/'),
         name='password_reset_confirm'),
         
    path('account/auth/password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),

    path('account/auth/sign-up/', views.Register.as_view(), name='signup'),
    path('account/auth/sign-up/cont/', views.Register2.as_view(), name='signup2'),
    path('account/auth/sign-up/completed/', views.SignUpCompleted.as_view(), name='signup_completed'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('lockscreen/', views.lockscreen, name='lockscreen'),
    path('dashboard/settings/', views.settings, name='settings'),
    path('dashboard/cadets/', views.cadets, name='cadets'),
    path('dashboard/cadet/<int:id>/profile/', views.cadet_profile, name='cadet_profile'),
    path('dashboard/cadet/messages/', views.cadet_messages, name='cadet_messages'),
    path('dashboard/supervisor/<int:id>/comments/add/', views.supervisor_comment, name='supervisor_comment'),
    path('dashboard/cadet/taskboard/', views.cadet_taskboard, name='cadet_taskboard'),
    path('dashboard/cadet/logbook/', views.cadet_logbook, name='cadet_logbook'),
    path('dashboard/cadet/create-logbook/', views.createlogbook, name='create_logbook'),
    path('dashboard/cadet/delete-logbook/', views.delete_logbook_entry, name='delete_logbook_entry'),
    path('dashboard/cadet/<int:id>/edit-logbook/', views.update_logbook_entry, name='update_logbook_entry'),
    path('dashboard/cadet/logbook/<int:id>/overview/', views.cadet_logbook_overview, name='cadet_logbook_overview'),
    path('dashboard/supervisors/', views.supervisors, name='supervisors_profile'),
    path('dashboard/timeline/', views.timeline, name='timeline'),
]

src/core/forms.py
import re
from .models import Cadetlogbook
from django import forms
from django.contrib.auth.models import User 

ACCOUNT_TYPE = (
    ('supervisor', 'Supervisor'),
    ('cadet', 'Cadet')
)


GENDER = (
    ('male', 'Male'),
    ('female', 'Female')
)


class UserRegistrationForm(forms.Form):
    email = forms.EmailField(required=True, max_length=50)
    first_name = forms.CharField(required=True, max_length=20)
    last_name = forms.CharField(required=True, max_length=20)
    gender = forms.CharField(required=True, max_length=20, widget=forms.Select(choices=GENDER))
    account_type = forms.CharField(required=True, max_length=20, widget=forms.Select(choices=ACCOUNT_TYPE))
    
    def clean_email(self):
        cd = self.cleaned_data
        email = cd['email']
        try:                                                     
            User.objects.get(email=email)
            raise forms.ValidationError("Sorry this email id already exists.")
        except User.DoesNotExist:
            pass

        return email


class RegistrationForm2(forms.Form):
    custom_error_message = str()
    username = forms.CharField(required=True)
    password = forms.CharField(min_length=10, max_length=100, required=True, widget=forms.PasswordInput)
    password2 = forms.CharField(min_length=10, max_length=100, required=True, widget=forms.PasswordInput)

    def clean_username(self):
        cd = self.cleaned_data
        username = cd['username']
        try:
            User.objects.get(username=username)
            raise forms.ValidationError(self.custom_error_message)
        except User.DoesNotExist:
            pass

        return username
    

    def clean(self):
        super().clean()
        cd = self.cleaned_data
        password = cd['password']
        password2 = cd['password2']
        symbol_regex = re.compile('[@_!#$%^&*()<>?/\|}{~:]')
        uppercase_regex = re.compile('[A-Z]')
        if password and password2:
            if (symbol_regex.search(password) is None) or (uppercase_regex.search(password) is None):
                raise forms.ValidationError("passwords must contain at least one uppercase and a symbol character.")
            else:
                if cd['password'] != cd['password2']:
                    raise forms.ValidationError("Passwords don't match.")


class SupervisorRegistrationForm(RegistrationForm2):
    custom_error_message = 'Sorry This Staff Id Already Exists.'



class CadetRegistrationForm(RegistrationForm2):
    custom_error_message = 'Sorry This Reg No Already Exists. '



class CadetLogbookModelForm(forms.ModelForm):
    
    class Meta:
        model = Cadetlogbook
        fields = ['work_title','department', 'description_of_work', 'end_date']


class SearchForm(forms.Form):
    keyword = forms.CharField(max_length=50, required=True, strip=True)


class SupervisorCommentModelForm(forms.ModelForm):

    class Meta:
        model = Cadetlogbook
        fields = ['work_status', 'comment']

src/cadet_logbook/views.py
from django.shortcuts import render


def error_404_view(request, exception):
    return render(request, '404.html')



def error_500_view(request):
    return render(request, '500.html')

src/core/views.py
from django.db.models import Q
from django.contrib import messages
from . models import Profile, Cadetlogbook
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from .forms import (
    UserRegistrationForm, SupervisorRegistrationForm, 
    CadetRegistrationForm, CadetLogbookModelForm,
    SearchForm, SupervisorCommentModelForm
)
#from .token_generator import account_activation_token
from django.contrib.auth.decorators import login_required
from django.core.paginator import (Paginator, EmptyPage, PageNotAnInteger)


class Register(FormView):
    template_name = 'core/signup.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy("core:signup2")

    def form_valid(self, form):
        self.request.session['user_data'] = self.request.POST
        return super().form_valid(form)



class Register2(FormView):
    custom_text_value = str()
    template_name = 'core/signup2.html'
    success_url = reverse_lazy("core:signup_completed")

    def get_form_class(self):
        if self.request.session['user_data'].get('account_type').upper() == 'Cadet':
            self.form_class = CadetRegistrationForm
            self.custom_text_value = "Cadet No"

        else:
            self.form_class = SupervisorRegistrationForm
            self.custom_text_value = "Supervisor No"

        return super().get_form_class()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['email'] = self.request.session['user_data'].get('email')
        context['account_type'] = self.request.session['user_data'].get('account_type')
        context['form'] = self.get_form()
        context['custom_text_value'] = self.custom_text_value
        return context

    def form_valid(self, form):
        email = self.request.session['user_data'].get('email')
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = User.objects.create_user(username, email, password)
        user.first_name = self.request.session['user_data'].get('first_name')
        user.last_name = self.request.session['user_data'].get('last_name')
        user.is_active = True
        profile = Profile()
        profile.user = user
        profile.account_type = self.request.session['user_data'].get('account_type')
        profile.gender = self.request.session['user_data'].get('gender')
        user.save()
        profile.save()
        return super().form_valid(form)
       # self.init_email_activation(email)
       # self.send_activation_mail()


class  SignUpCompleted(TemplateView):
    template_name = 'core/signup_completed.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['email'] = self.request.session['user_data'].get('email')
        return context


@login_required
def dashboard(request):
    profile = get_object_or_404(Profile, user=request.user)

    if profile.account_type == 'supervisor':
        return render(request, 'core/supervisor_admin_dashboard.html', {
            'profile' : profile
        })

    else:
        return render(request, 'core/cadet_admin_dashboard.html', {
            'profile' : profile
        })


@login_required
def settings(request):
    profile = get_object_or_404(Profile, user=request.user)
    return render(request, 'core/settings.html', {
        'profile': profile
    })


def lockscreen(request):
    return render(request, 'core/lockscreen.html', {})


@login_required
def cadets(request):
    profile = get_object_or_404(Profile, user=request.user)
 
    return render(request, 'core/cadets.html', {
        'profile':profile,
       
    })


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

@login_required
def delete_logbook_entry(request):
    if request.method == "POST" and is_ajax(request=request):
        logbook_id = request.POST.get('entry_id')
        logbook_entry = Cadetlogbook.objects.get(id=logbook_id)
        logbook_entry.delete()
        return JsonResponse({"message": "Logbook Entry Successfully Deleted"}, status=200)

    else:
        return JsonResponse({'errors' : 'Failed to process request, please try again later'}, status=404)

@login_required
def update_logbook_entry(request, id):
    profile = get_object_or_404(Profile, user=request.user)
    logbook_instance = get_object_or_404(Cadetlogbook, id=id)
    form = CadetLogbookModelForm(request.POST or None, instance=logbook_instance)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, "Logbook Successfully Updated")
            return HttpResponseRedirect("/dashboard/cadet/logbook/")

    return render(request, 'core/update_logbook.html', {
        'form' : form, 
        'profile' : profile,
        'logbook_instance' : logbook_instance.id
    })


@login_required
def cadet_profile(request):
    profile = get_object_or_404(Profile, user=request.user)
    return render(request, 'core/profile.html', {
        'profile':profile
    })

@login_required
def cadet_messages(request):
    profile = get_object_or_404(Profile, user=request.user)
    return render(request, 'core/message.html', {
        'profile':profile
    })

@login_required
def cadet_taskboard(request):
    profile = get_object_or_404(Profile, user=request.user)
    return render(request, 'core/taskboard.html', {
        'profile':profile
    })



def is_valid_queryparam(param):
    return param != '' and param is not None

@login_required
def cadet_logbook(request):
    cadet_logbooks = None
    search_form =  SearchForm(request.GET)
    keyword = request.GET.get('keyword') 
    profile = get_object_or_404(Profile, user=request.user)

    if profile.account_type == 'cadet':
        cadet_logbooks = Cadetlogbook.objects.filter(user=request.user)
    
    else: 
        cadet_logbooks = Cadetlogbook.objects.all() 

    if is_valid_queryparam(keyword):
        cadet_logbooks = Cadetlogbook.published.filter(
            Q(work_title__icontains=keyword)|
            Q(description_of_work__icontains=keyword) |
            Q(user__first_name__icontains=keyword) | 
            Q(user__last_name__icontains=keyword) 
        ).distinct()

    
    paginator = Paginator(cadet_logbooks, 2)
    page = request.GET.get('page')

    try:
        cadet_logbooks = paginator.page(page)

    except PageNotAnInteger:
        cadet_logbooks = paginator.page(1) 

    except EmptyPage:
        cadet_logbooks = paginator.page(paginator.num_pages)

    return render(request, 'core/cadet_logbook.html', {
        'profile': profile,
        'page': page,
        'search_form': search_form,  
        'cadet_logbooks' : cadet_logbooks
    })


@login_required
def supervisor_comment(request, id):
    logbook_instance = get_object_or_404(Cadetlogbook, id=id)
    form = SupervisorCommentModelForm(request.POST or None, instance=logbook_instance)
    if request.method == 'POST':
        if form.is_valid():
            instance =  form.save(commit=False) 
            instance.supervisor = request.user
            instance.save()
            messages.success(request, "Comment Updated")
            return HttpResponseRedirect("/dashboard/cadet/logbook/")

        else:
            messages.success(request, "Failed to update comment")
            return HttpResponseRedirect("/dashboard/cadet/logbook/")


@login_required
def createlogbook(request):
    profile = get_object_or_404(Profile, user=request.user)
    form = CadetLogbookModelForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            messages.success(request, "Logbook Successfully Created")
            return HttpResponseRedirect("/dashboard/cadet/logbook/")
        else:
            messages.error(request, "Logbook failed to save")
            return HttpResponseRedirect("/dashboard/cadet/logbook/")

    return render(request, 'core/create_logbook.html', {
        'profile': profile,
        'form' : form
    })


@login_required
def cadet_logbook_overview(request, id):
    profile = get_object_or_404(Profile, user=request.user)
    cadet_logbook = get_object_or_404(Cadetlogbook, pk=id)
    return render(request, 'core/cadetlogbook_overview.html', {
        'profile': profile,
        'cadet_logbook' : cadet_logbook 
    })

@login_required
def supervisors(request):
    profile = get_object_or_404(Profile, user=request.user)
    return render(request, 'core/supervisors.html', {
        'profile': profile
    })

@login_required
def supervisor_profile(request):
    profile = get_object_or_404(Profile, user=request.user)
    return render(request, 'core/supervisor_profile.html', {
        'profile': profile
    })


@login_required
def timeline(request):
    profile = get_object_or_404(Profile, user=request.user)
    return render(request, 'core/timeline.html', {
        'profile':profile
    })


def forgot_password(request):
    return render(request, 'core/forgot_password.html', {})

src/core/templates/core/create_logbook.html
{% extends 'core/base.html' %}

{% load static %}
{% load widget_tweaks %}


{% block title %}  Dashboard | CadetLogbook  {% endblock title %}

{% block css %}

    <link href="{% static 'assets/libs/flatpickr/flatpickr.min.css' %}" rel="stylesheet" type="text/css">
            
{% endblock css %}

{% block header %}

    {% include 'header.html' with user_profile=profile %}

{% endblock header %}

{% block content %}

<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0">New Logbook Entry</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Logbook</a></li>
                        <li class="breadcrumb-item active">Create Entry</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div>
                        <ul class="wizard-nav mb-5">
                            <li class="wizard-list-item">
                                <div class="list-item active">
                                    <div class="step-icon" data-bs-toggle="tooltip" data-bs-placement="top">
                                        <i class="uil uil-clipboard-notes"></i>
                                    </div>
                                </div>
                            </li>
                            <li class="wizard-list-item">
                                <div class="list-item">
                                    <div class="step-icon" data-bs-toggle="tooltip" data-bs-placement="top">
                                        <i class="uil uil-users-alt"></i>
                                    </div>
                                </div>
                            </li>

                            <li class="wizard-list-item">
                                <div class="list-item">
                                    <div class="step-icon" data-bs-toggle="tooltip" data-bs-placement="top">
                                        <i class="uil uil-paperclip"></i>
                                    </div>
                                </div>
                            </li>
                        </ul>
                        <!-- wizard-nav -->

                        <div class="wizard-tab" style="display: block;">
                            <div class="text-center mb-4">
                                <h5>Create CadetLogbook</h5>
                                <p class="card-title-desc">Fill all information below</p>
                                <span style="color: red;">{{ form.non_field_errors }}</span>
                            </div>
                            <form action="{% url 'core:create_logbook' %}" method="POST" onsubmit='disableButton()'>
                                {% csrf_token %}
                               
                                <div>
                                    <span style="color:red">{{ form.work_title.errors}}</span>
                                    <div class="mb-3">
                                        
                                        <label for="work_title" class="form-label">Work Title</label>
                                        {% render_field form.work_title id="work_title" type="text" class="form-control" placeholder="Work Title" %}
                                    </div>

                                    <span style="color:red">{{ form.form.description_of_work.errors}}</span>
                                    <div class="mb-3">
                                        <label for="projectdesc" class="form-label">Description Of Work Done</label>
                                        {% render_field form.description_of_work class="form-control" id="projectdesc" rows="3" placeholder="Work Description..." %}
                                    
                                    </div>
                                    
                                    
                                    
                                    <span style="color:red">{{ form.department.errors}}</span>
                                    <div class="mb-3">
                                        <label for="cadet_department" class="form-label"> Department: </label>
                                        {% render_field form.department class="form-select form-control"  id="cadet_department" placeholder="Department" %}
                                    </div>  


                                    <span style="color:red">{{ form.end_date.errors}}</span>
                                    <div class="mb-3">
                                        <label class="form-label"> End Date : </label>
                                        {% render_field form.end_date type="date" class="form-control" id="date" %}
                                    </div> 

                                </div>

                                <div class="d-flex align-items-start gap-3 mt-4">
                                    <button type="submit" id='btn' class="btn btn-primary w-sm ms-auto">Add Logbook</button>
                                </div>

                            </form>
                        </div>
                        

                    
                    </div>
                </div><!-- end card body -->
            </div><!-- end card -->
        </div><!-- end col -->
    </div><!-- end row --> 
</div>
 
{% endblock content %}

{% block script %}

    <script src="{% static 'assets/libs/flatpickr/flatpickr.min.js' %}"></script>

    <!-- init js -->
    <script src="{% static 'assets/js/pages/project-create.init.js' %}"></script>

    <script src="{% static 'assets/js/app.js' %}"></script>

<script>
    function disableButton() {
        var btn = document.getElementById('btn');
        btn.disabled = true;
        btn.innerText = 'Please Wait...'
    }
</script>

{% endblock script %}

src/core/templates/core/signup.html
{% load static %}
{% load widget_tweaks %}
<!doctype html>
<html lang="en">

    

<head>
        
        <meta charset="utf-8" />
        <title>Signup | CadetLogbook</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="Pichforest" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="assets/images/favicon.ico">

        <!-- Bootstrap Css -->
        <link href="{% static 'assets/css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'assets/css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />

    </head>

    
    <body class="body-img">

    <!-- <body data-layout="horizontal"> -->

        <div class="authentication-bg min-vh-100">
            <div class="bg-overlay bg-white"></div>
            <div class="container">
                <div class="d-flex flex-column min-vh-100 px-3 pt-4">
                    <div class="row justify-content-center my-auto">
                        <div class="col-md-8 col-lg-6 col-xl-4">
                            <div class="text-center py-5">
                                <div class="mb-4 mb-md-5">
                                    <a href="{% url 'core:home' %}" class="d-block auth-logo">
                                        <img src="{% static 'assets/images/dashboard_logo.png' %}" alt="" height="100" class="auth-logo-dark">
                                        <img src="{% static 'assets/images/dashboard_logo.png' %}" alt="" height="100" class="auth-logo-light">
                                    </a>
                                </div>
                                <div class="mb-4">
                                    <h5 class="">Register Account</h5>
                                    <p>Create your cadetlogbook account!</p>
                                </div>
                                <form method="POST" action="{% url 'core:signup'  %}"  onsubmit='disableButton()'>
                                    <span style="color: red;">{{ form.non_field_errors }}</span>
                                    {% csrf_token %}
                                    <span style="color:red">{{ form.email.errors}}</span>
                                    <div class="form-floating form-floating-custom mb-3">
                                        {% render_field form.email  class="form-control" id="input-email" placeholder="Enter Email" %}
                                        <label for="input-email">Email</label>
                                        <div class="form-floating-icon">
                                            <i class="uil uil-envelope-alt"></i>
                                        </div>
                                    </div>

                                    <span style="color:red">{{ form.first_name.errors}}</span>
                                    <div class="form-floating form-floating-custom mb-3">
                                        {% render_field form.first_name class="form-control" id="input-first_name"  placeholder="First Name" %}
                                        <label for="input-first_name">First Name</label>
                                        <div class="form-floating-icon">
                                            <i class="uil-user"></i>
                                        </div>
                                    </div>

                                    <span style="color:red">{{ form.last_name.errors}}</span>
                                    <div class="form-floating form-floating-custom mb-3">
                                        {% render_field form.last_name class="form-control" id="input-last_name"  placeholder="Last Name" %}
                                        <label for="input-last_name">Last Name</label>
                                        <div class="form-floating-icon">
                                            <i class="uil-user"></i>
                                        </div>
                                    </div>

                                   
                                    
                                    <div class="form-floating form-floating-custom mb-3">
                                        {% render_field  form.gender class="form-select form-control"  id="Gender" placeholder="Gender"  %}
                                        
                                        <label for="Gender">Gender</label>
                                        <div class="form-floating-icon">
                                            <i class="uil-users-alt"></i>
                                        </div>

                                        
                                    </div>
                                    
                                    <span style="color:red">{{ form.account_type.errors}}</span>
                                    <div class="form-floating form-floating-custom mb-3">
                                        {% render_field  form.account_type class="form-select form-control"  id="Gender" placeholder="Accounttype"  %}
                                        
                                        <label for="Accounttype">Account Type</label>
                                        <div class="form-floating-icon">
                                            <i class="uil-book-open"></i>
                                        </div>

                                        
                                    </div>

    

                                    <div class="mt-3">
                                        <button id="btn" class="btn btn-info w-100" type="submit">Continue</button>
                                    </div>
                                </form><!-- end form -->

                                <div class="mt-5 text-center">
                                    <p>Already have an account ? <a href="{% url 'core:home' %}" class="fw-medium text-decoration-underline"> Signin </a></p>
                                </div>
                            </div>
                        </div><!-- end col -->
                    </div><!-- end row -->

             

                </div>
            </div><!-- end container -->
        </div>
        <!-- end authentication section -->

        <!-- JAVASCRIPT -->

        <script>
            function disableButton() {
                var btn = document.getElementById('btn');
                btn.disabled = true;
                btn.innerText = 'Please Wait...'
            }
        </script>
        <script src="{% static 'assets/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets/libs/metismenujs/metismenujs.min.js' %}"></script>
        <script src="{% static 'assets/libs/simplebar/simplebar.min.js' %}"></script>
        <script src="{% static 'assets/libs/feather-icons/feather.min.js' %}"></script>

    </body>


</html>

src/core/templates/core/taskboard.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %} Taskboard | CadetLogbook {% endblock title %}

{% block header %}

    {% include 'header.html' with user_profile=profile %}

{% endblock header %}

{% block content %} 

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="d-flex flex-column min-vh-100">
                <div class="text-center my-auto py-5">
                    <div class="row justify-content-center mb-5">
                        <div class="col-sm-4">
                            <div class="maintenance-img">
                                <img src="{% static 'assets/images/maintenance.png' %}" alt="" class="img-fluid mx-auto d-block">
                            </div>
                        </div>
                    </div>
                    <div class="text-muted mb-5">
                        <h4>Sorry you have no tasks yet!</h4>
                        <p>Please check back when you have completed tasks.</p>
                    </div>

                    <!-- end row -->
                </div>

           
            </div>
        </div>
        <!-- end col -->
    </div>
    <!-- end row -->
</div>

{% endblock content %}